name: Generate CV PDF

on:
  push:
    branches:
      - main
    paths:
      - 'sys/cv/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markdown2 weasyprint pygments pypdf2

    - name: Generate CV PDFs
      run: |
        python markdown_to_pdf.py

    - name: Upload PDF artifacts
      uses: actions/upload-artifact@v2
      with:
        name: cv-pdfs
        path: sys/pdf/*.pdf
